name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to Azure
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          client-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}  # Extract clientId from the credentials JSON
          tenant-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}  # Extract tenantId from the credentials JSON
          subscription-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}  # Extract subscriptionId from the credentials JSON

      # Build and push Docker image to ACR
      - name: 'Build and Push Docker image'
        run: |
          docker build -t ${{ fromJson(secrets.AZURE_CREDENTIALS).acrName }}.azurecr.io/fastapi-app:latest .
          docker push ${{ fromJson(secrets.AZURE_CREDENTIALS).acrName }}.azurecr.io/fastapi-app:latest

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: trywebappcicd  # Name of the Web App
          slot-name: production    # Use "production" if deploying to the main slot
          images: ${{ fromJson(secrets.AZURE_CREDENTIALS).acrName }}.azurecr.io/fastapi-app:latest  # Image to deploy
