name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to Azure
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}  # Secret holding Service Principal credentials

      # Build and push Docker image to ACR
      - name: 'Build and Push Docker image'
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/fastapi-app:latest .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/fastapi-app:latest

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: trywebappcicd  # Name of the Web App
          slot-name: production    # Use "production" if deploying to the main slot
          images: ${{ secrets.ACR_NAME }}.azurecr.io/fastapi-app:latest  # Image to deploy
