name: Build and Deploy FastAPI App to Azure

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/fastapi-cicd:latest .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/fastapi-cicd:latest

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Azure Web App if not exists
      run: |
        az webapp show --name ${{ secrets.WEBAPP_NAME }} || az webapp create --name ${{ secrets.WEBAPP_NAME }} --plan ${{ secrets.AZURE_PLAN }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --deployment-container-image-name ${{ secrets.ACR_NAME }}.azurecr.io/fastapi-cicd:latest

    - name: Deploy to Azure Web App
      run: |
        az webapp config container set --name ${{ secrets.WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --docker-custom-image-name ${{ secrets.ACR_NAME }}.azurecr.io/fastapi-cicd:latest
